version: "3.7"
services:
  web:
    build: .
    command: /start-reload.sh
    volumes:
      - ./src/app:/app
    ports:
      - 8080:80
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - APP_MODULE=main:app
      - HOST=0.0.0.0
      - PORT=80
      - LOG_LEVEL=debug
